### ISSUE TITLE
Cookie strap remains on all pages until you accept/reject

### ISSUE THREAD

**Issue by robertcreaner** [Alex-D/Cookies-EU-banner#10]
Hi Alex,

I have the cookie banner code in my index.html and it's working fine but I want the banner to remain across my entire site until the user actually responds to it. Right now when I navigate to a different page it disappears. Do I need to put the cookie banner on every page? Is the functionality there to hide the cookie banner when its responded to on the previous page? 

Thanks,
Robert.

**Comment by Alex-D** [comment]
Hi!
You need to have both the script and the HTML code on each page, then you can take a look at the *Options* part of the doc : http://alex-d.github.io/Cookies-EU-banner/#documentation

What you need is the only one option of the plugin :)
