### ISSUE TITLE
Debug option?

### ISSUE THREAD

**Issue by jenstornell** [Alex-D/Cookies-EU-banner#16]
I just tried it and it seems to be great but I clicked the buttons on my localhost and I guess it saved the cookies and I can't get the banner back to debug / design it (without wiping out the cookies every time).

It's great that it's so small but I still wish for a debug feature. Maybe something like this?

```html
<div id="cookies-eu-banner" style="display: none;" data-debug="true">
```

With the debug, the bar always comes back after refresh.

It's not been updated in a while. Do you still consider it an active repo?

**Comment by Alex-D** [comment]
> Do you still consider it an active repo?

**Comment by jenstornell** [comment]
Agree! Simplicity wins! ☺

**Comment by jenstornell** [comment]
Just wanted to let you know. One of the biggest advantages with your solution is the size. I also wrote about it here (before I switched to yours):

https://github.com/insites/cookieconsent/issues/154

>3.5kb is almost nothing but having a js of more than 17kb just to display a cookie message is quite much, I think.

**Comment by Alex-D** [comment]
Cookies-EU-banner is a 2.35kb plugin of vanilla JS :)
https://github.com/Alex-D/Cookies-EU-banner/blob/c1832d1b19d8cd7de2d47dd75993f8c505bee7b0/dist/cookies-eu-banner.min.js
