### ISSUE TITLE
Does not disable banner for Google bot

### ISSUE THREAD

**Issue by jenstornell** [Alex-D/Cookies-EU-banner#17]
>Disables banner when visitor is a bot : prevents SEO Engines to confuse your cookie advert message with the main content of your pages;

I tried https://developers.google.com/speed/pagespeed/insights/ today and the above does not seems to be correct.

**Look below:**

![pagespeed insights](https://cloud.githubusercontent.com/assets/927011/18467237/6fe95938-799f-11e6-87f6-ceb030f3318a.png)

It shows the banner and it uses the js to do it because I set display to none, just like your example. Just wanted to let you know that the banner seems to be crawlable after all.

**Comment by Alex-D** [comment]
https://github.com/Alex-D/Cookies-EU-banner/blob/master/src/cookies-eu-banner.js#L20

There is a new user agent maybe :/

**Comment by Alex-D** [comment]
I've made a test. PageSpeed use a classic browser and is not exactly a bot since you trigger it.
