### ISSUE TITLE
banner does not execute on safari .1.2 (11601.7.7) and firefox (48.0.2) on Mac (El Capitan)

### ISSUE THREAD

**Issue by prtome** [Alex-D/Cookies-EU-banner#18]
Hello

I have tested my site (for now it is local) with Chrome, Firefox and Safari on a Mac. With Chrome everything works perfectly, with Safari and Firefox  I don't see the banner  and no error message in console.

Would you have any idea of what might be wrong with those browsers? thanks

Update: my safari had "not track " on, once off it works.
Firefox still does not work, even after taking away not track and any other kind of block. 
The only cookie I sue are those of Google Analytics. Does that mean that if the banner is not shown, then there is no tracking done ? which would be ok vs the law I presume. thanks

**Comment by Alex-D** [comment]
I can't test for now, I will check that ASAP.

**Comment by prtome** [comment]
Thanks.

 I had checked the cookies, and deleted all without seeing the banner.
In the end I also deleted the history, and now I can see it.
Don't know, maybe there is some weird setup on my Mac, I am asking friends to check with their computers, now that it is on line (www.nurideas.com)
Thanks again

**Comment by Alex-D** [comment]
That seems to be a bug on your side so.
