### ISSUE TITLE
Version 1.2.9 not on npmjs

### ISSUE THREAD

**Issue by PouleR** [Alex-D/Cookies-EU-banner#24]
I'm facing the same problem as described in #23, however I can't install version 1.2.9 via NPM since 1.2.8 is the latest release available. Can you make 1.2.9 available ?

**Comment by Alex-D** [comment]
You right, last build sucess but did not success the deploy stage :/
I'll check that ASAP.

**Comment by Alex-D** [comment]
Done :)
Thanks for report!

**Comment by PouleR** [comment]
Thanks! However it looks like the dist directory is missing and therefore I can't use it in my project since the dist files can't be found when requiring it (import CookiesEuBanner from 'cookies-eu-banner';)

I don't have this problem with version 1.2.8

**Comment by Alex-D** [comment]
Rooo I've fail ><
I will fix that

**Comment by PouleR** [comment]
That would be great, thanks!
