### ISSUE TITLE
Version 1.2.9 no dist folder on bower install

### ISSUE THREAD

**Issue by yamelkaya** [Alex-D/Cookies-EU-banner#25]
No folder `cookies-eu-banner/dist/` with js files when install plugin with command:

`bower install cookies-eu-banner --save`

For version 1.2.8 everything is ok.

**Comment by Alex-D** [comment]
Yep, I know, I need to make a new publish, sorry about that :/

**Comment by Alex-D** [comment]
It should be OK with the new 2.1.10 now :)
