### ISSUE TITLE
Uncaught ReferenceError: CookiesEuBanner is not defined

### ISSUE THREAD

**Issue by mrpacman101** [Alex-D/Cookies-EU-banner#31]
Hello @Alex-D, 

i have downloaded the latest files from your repo. I opened your demo.html page and straight up got this error in the console:
Uncaught ReferenceError: CookiesEuBanner is not defined
    at index.html:35

The JS file in my case was loaded from a cdn and it did load the JS (https://cdn.shopify.com/s/files/1/2252/6495/t/1/assets/cookies-eu-banner.js?11990101471996168049) but still it says not defined. 

With my limited JS Skills i now reach out to you - you can see it in action here https://www.soundpost.com  - if you check the source code and search for "Alex D" you should see my implementation is correct. 

Help would be really appreciated. 

Cheers

**Comment by suttree** [comment]
I'm not sure if this is the same issue, but you could try an older version (1.2.8) to get the dist folder - https://github.com/Alex-D/Cookies-EU-banner/issues/24

**Comment by mrpacman101** [comment]
*gosh* the timing of the JS loading was wrong ... now it loads the script and all is good - very nice script and light, thanks 👍
