### ISSUE TITLE
Latest release references dist/cookies-eu-banner.js which doesn't exist.

### ISSUE THREAD

**Issue by SiAshbery** [Alex-D/Cookies-EU-banner#34]
The `main` parameter in `package.json` refers to `dist/cookies-eu-banner.js`, which isn't included in the release itself, and as such hasn't been working properly for us unless we manually run `npm run build` in the downloaded node module.

Release `1.2.10` Included the `dist/` folder and works fine as a result. Was there a specific reason it was removed and included in `.gitignore`?

Would it be easier to point main to `src/cookies-eu-banner.js` instead?

**Comment by Alex-D** [comment]
You right, I've just released the 1.2.14 which should fix that :)

**Comment by rubycon** [comment]
@Alex-D same issue with the latest release 1.2.15.

**Comment by Alex-D** [comment]
Should be fixed in 1.2.16.

Sorry again ^^'

**Comment by rubycon** [comment]
It works great now! Thanks.

**Comment by DRicciardi** [comment]
Same issue now. The demo is also referencing dist/cookies-eu-banner.min.js so it doesn't work when you download the release.

**Comment by Alex-D** [comment]
The file is here in the latest release: https://github.com/Alex-D/Cookies-EU-banner/blob/1.2.16/dist/cookies-eu-banner.min.js

I did not understand your point :/

**Comment by DRicciardi** [comment]
Oh, I just used the download link and I didn't see the dist folder in the master branch.

No biggie. Thanks for your work!
