### ISSUE TITLE
Readme or site needs screenshot of banner in use

### ISSUE THREAD

**Issue by paul-hammant** [Alex-D/Cookies-EU-banner#36]

**Comment by Alex-D** [comment]
Since the plugin is more JS that CSS, you should redesign it to fit to your site.

I can add a screenshot too, but think it customizable :)

**Comment by paul-hammant** [comment]
Agree, but in terms of 'conversion', you'll get a 2x or a 3x more users if they can quickly see what it looks like in the readme.  Remember: drag an image (from file system) to new github issue (browser) to get lasting url for it.

**Comment by jenstornell** [comment]
I agree, a screenshot is good marketing. It gives a hint of how it *may* look like in the end.

**Comment by Alex-D** [comment]
Done
