### ISSUE TITLE
banner not realod if cookie "hasConsent" set to false

### ISSUE THREAD

**Issue by sudhir600** [Alex-D/Cookies-EU-banner#37]
Hi Alex, Great work. 
BDW, I found a minor bug that, if any script or manually change cookie value ` "hasConsent=false`" and then refresh the page, it didn't show cookie banner. when i simply empty the `hasConsent` value, it start showing banner. so my point is either empty value or false is convey the same meaning for banner. isn't?

why not put an eventLister,
I don't know how to listen cookie change but recently  i work on how to detect any changes happen in LocalStorage. 

```
window.addEventListener("storage", function (e) {
	//reload banner();
});
```

Hope you will find any solution for cookie for too.

![image](https://user-images.githubusercontent.com/4952560/43133504-a1402ef6-8f5c-11e8-8d52-b3c3f4094326.png)

**Comment by Alex-D** [comment]
Since the code contains that: 

https://github.com/Alex-D/Cookies-EU-banner/blob/87f64f64e6c3d4c25616fd9edbfd27af9fbf3ebc/src/cookies-eu-banner.js#L95-L103

**Comment by Alex-D** [comment]
As I re-read this issue, I think I understand your point: you are about to say that false and null are the same, but... no. False says that you decline; true, you accept, and null you had not make a choice yet.

So, behavior is OK and it's not a bug.
