### ISSUE TITLE
Bar doesn't show up

### ISSUE THREAD

**Issue by UisgeBeatha436** [Alex-D/Cookies-EU-banner#41]
Followed the install instructions. Used npm to install. However the bar doesn't show, but as soon as I remove the 'display: none;' the bar shows up. What can I do to investigate?

Thanks!

**Comment by Alex-D** [comment]
Hey, did you follow Readme instructions? Did you put ids as needed (`cookies-eu-banner`)?

Show a sample HTML of your code please.

**Comment by UisgeBeatha436** [comment]
Thanks for your reply. Did follow the instructions. Please have a look at both screenshots.
<img width="796" alt="schermafbeelding 2018-11-19 om 08 22 45" src="https://user-images.githubusercontent.com/37063702/48695452-78b28580-ebdf-11e8-8cb6-948bfc04357e.png">
<img width="978" alt="schermafbeelding 2018-11-19 om 09 36 07" src="https://user-images.githubusercontent.com/37063702/48695456-7b14df80-ebdf-11e8-88d1-2638dda5b058.png">

**Comment by Alex-D** [comment]
Did you have Do Not Track enabled?

I think you are here: 

https://github.com/Alex-D/Cookies-EU-banner/blob/master/src/cookies-eu-banner.js#L36-L38

**Comment by UisgeBeatha436** [comment]
Sorry to re-open. Took the example code from Github, including the links, installed according, I do see "LOAD GA", but no bar is showing up. Site is based on Bootstrap Twitter and on localhost. 

Do you have any suggestions what I can to get the bar to show up?

Thank you!

**Comment by Alex-D** [comment]
If the callback is running, that means you need to clean the consent cookie to show back the bar.

**Comment by UisgeBeatha436** [comment]
Thanks. I've been looking for the consent cookie, however I'm not sure about the name. Could you post the name of the cookie? 
Thanks.

**Comment by Alex-D** [comment]
`hasConsent` as you can see here: https://github.com/Alex-D/Cookies-EU-banner/blob/1.2.16/src/cookies-eu-banner.js#L25

**Comment by UisgeBeatha436** [comment]
Thanks 👍
